# Generated by Django 3.1.3 on 2021-02-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210130_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='taskrel',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='taskrel',
            name='Target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='taskrel',
            name='Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
