# Generated by Django 3.1.3 on 2021-02-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210215_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrel',
            name='Type',
        ),
    ]
