# Generated by Django 3.1.3 on 2021-02-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_taskrel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='wbs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.wbs'),
        ),
    ]
