# Generated by Django 3.1.3 on 2021-02-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210216_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskstate', models.CharField(blank=True, max_length=60, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.task')),
            ],
        ),
    ]
