# Generated by Django 3.1.3 on 2021-02-18 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_taskuseractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuseractivity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
