# Generated by Django 3.1.3 on 2021-02-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_taskuseractivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuseractivity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 2, 18)),
        ),
    ]
