# Generated by Django 3.1.3 on 2021-02-18 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210218_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuseractivity',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
