# Generated by Django 3.1.3 on 2021-02-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectemployeerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
