# Generated by Django 3.1.3 on 2021-04-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_wbs_is_root'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrel',
            old_name='Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='taskrel',
            old_name='Target',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='taskrel',
            old_name='Type',
            new_name='type',
        ),
    ]
