# Generated by Django 3.1.3 on 2021-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_taskrel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrel',
            name='Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
