# Generated by Django 3.1.3 on 2021-02-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_taskuseractivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrel',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='taskrel',
            name='Target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='taskuseractivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
        ),
    ]
