# Generated by Django 3.1.3 on 2021-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
